In [41]:
import os
import pandas as pd

In [6]:
print(os.getcwd())

C:\Users\katri

In [7]:
data_frame = pd.read_csv(r'...\archive\online_retail.csv')

In [8]:
data_frame.head()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [9]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   index        541909 non-null  int64
 1   InvoiceNo    541909 non-null  object
 2   StockCode    541909 non-null  object
 3   Description  540455 non-null  object
 4   Quantity     541909 non-null  int64
 5   InvoiceDate  541909 non-null  object
 6   UnitPrice    541909 non-null  float64
 7   CustomerID   406829 non-null  float64
 8   Country      541909 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 37.2+ MB

In [21]:
data_frame.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,540455.000000,540455,540455.000000,406829.000000
mean,9.603129,2011-07-04 16:20:42.947035392,4.623519,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:49:00,1.250000,13953.000000
50%,3.000000,2011-07-20 11:38:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:49:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.007598,NaN,96.889628,1713.600303

In [11]:
data_frame.isnull().sum()

index               0
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
data_frame.duplicated().sum()

np.int64(0)

In [ ]:
## Varialbe Description has 1454 null values, so it will be deleted. Because, that number is negligible low in compare with 541909 rows.
## CustomerID has almost one quater of null values, those will be saved.

In [13]:
data_frame.dropna(subset=['Description'], inplace=True)

In [ ]:
## Date column- InvoiceDate will be transformed.

In [14]:
data_frame['InvoiceDate'] = pd.to_datetime(data_frame['InvoiceDate'])

In [15]:
data_frame.head(3)

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom

In [16]:
# column index is redundant.
data_frame.drop(columns=['index'], inplace=True)

In [18]:
data_frame.tail(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [23]:
(data_frame["Quantity"] <= 0).sum()

np.int64(9762)

In [ ]:
##This may indicate cancelation/return.

In [27]:
#Check cancelation invoice
data_frame[data_frame["Quantity"] <= 0]["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
True     9288
False     474
Name: count, dtype: int64

In [29]:
sales_data = data_frame[
    (data_frame["Quantity"] > 0) &
    (data_frame["UnitPrice"] > 0)
].copy()
## sales_data = valid sales transactions that you use for revenue analysis.

In [35]:
(data_frame["UnitPrice"] <= 0).sum()

np.int64(1063)

In [36]:
(data_frame["UnitPrice"] == 0).sum()

np.int64(1061)

In [ ]:
## Those articles with unit price 0 will not bring any revenue,but with negative will distort a financial statement.

In [37]:
sales_data = data_frame[
    (data_frame["Quantity"] > 0) &
    (data_frame["UnitPrice"] > 0)
].copy()
## sales_data = valid sales transactions that you use for revenue analysis.

In [ ]:
## When revenue will be calculated as quantity*unitPrice don't want to make mistakes.

In [38]:
sales_data['Revenue'] = sales_data["Quantity"]+sales_data["UnitPrice"]

In [39]:
sales_data.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,8.55
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,9.39
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,10.75

In [42]:
sales_data.to_csv('clean_data.csv', index=False)